### ISSUE TITLE
Cannot run REPL using `flabbergast-compiler` module resolved from Maven Central

### ISSUE THREAD

**Issue by pniederw** [apmasell/flabbergast#44]
Resolved `flabbergast-compiler:0.8` from Maven Central (with a fixed dependency declaration for `flabbergast-runtime`)

Executed `java -cp "flabbergast-compiler-0.8.jar:asm-5.0.3.jar:jline-2.12.1.jar:flabbergast-runtime-0.8.jar:commons-cli-1.2.jar" flabbergast.MainREPL`

```
Exception in thread "main" java.lang.NoClassDefFoundError: jline/Completor
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
	at java.lang.Class.getMethod0(Class.java:2866)
	at java.lang.Class.getMethod(Class.java:1676)
	at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: jline.Completor
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
```

Indeed, `jline-2.12.1` does not have a `jline.Completor` class. Is a different JLine version required than that listed in the flabbergast-compiler POM?

PS: The flabbergast-compiler Jar has a hardcoded Class-Path (`/usr/local/share/java/flabbergast-runtime-0.8.jar /usr/sha
 re/java/asm4.jar /usr/share/java/commons-cli.jar`) in its MANIFEST.MF (which even lists a different ASM version), which is probably not desirable.

PPS: A smoke test for the Maven modules seems to be missing.

**Comment by apmasell** [comment]
The build happens against Debian's Java packages, rather than what is on Maven Central. I have no idea how to use Maven, so it's all build through `make`. I think the problem is that Debian is using JLine 1.x and Maven Central only has JLine 2.x.

This is why there are no smoke tests. There's no Maven build. If you'd like to create a proper Maven build, I'd be very appreciative. Otherwise, I'm not sure how to proceed.

**Comment by pniederw** [comment]
Unfortunately I can't contribute to OSS at the moment (even though I have a strong OSS background). The best I can do is file accurate bug reports.

Which JLine version is required? Maven Central has all versions since 0.9 (http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22jline%22%20AND%20a%3A%22jline%22). Apparently there was no 1.x, but they went from 1.0 straight to 2.6 (I've double-checked this on their SourceForge page).

**Comment by apmasell** [comment]
Hmm. 1.2 is the version Debian has. There are JLine 2.11 libraries for Debian. I'll try porting to those.

**Comment by pniederw** [comment]
Switching to JLine 1.0 worked for me.

**Comment by apmasell** [comment]
Okay. I'll still try to port to a new version.
